import React from 'react';
import type { Metadata } from 'next';

import '@/styles/index.scss';

import { Mulish } from 'next/font/google';

export const mulish = Mulish({
  subsets: ['latin'],
  display: 'swap',
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  keywords: [],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      data-theme="light"
    >
      <body className={mulish.className}>{children}</body>
    </html>
  );
}
